coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 56%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
       # advanced settings
        branches: 
          - main
        if_ci_failed: error
        informational: false
        only_pulls: false
