version: "3.8"

services:
  sut:
    container_name: auth-tests
    build:
      context: .
      target: tests
    volumes:
      - ./src:/code
      - ./shared:/code/shared
      - ./shared/logs:/code/shared/logs
    env_file:
      - .env.sample
    environment:
      - TESTING=True

  db:
    image: postgres:13
    container_name: auth-postgres
    env_file:
      - .env.sample
    expose:
      - "5432"
