version: "3.8"

services:
  sut:
    container_name: auth-tests
    build:
      context: ""
    volumes:
      - ./src:/code
      - ./shared:/code/shared
      - ./shared/logs:/code/shared/logs
    env_file:
      - .env
    environment:
      - TESTING=False
