name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
#     - uses: actions/checkout@v2
#     - name: Unit tests
    - id: step1
      run: cat /home/runner/work/Auth_sprint_1/Auth_sprint_1/.env.sample > /home/runner/work/Auth_sprint_1/Auth_sprint_1/.env
    - id: step2
      run: docker-compose -f docker-compose.test.yaml up --build --exit-code-from sut
