name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Unit tests
      env:
        PROJECT_NAME: auth
        SETTINGS: dev
        BASIC_AUTH_USERNAME: user
        BASIC_AUTH_PASSWD: passwd
        ALLOWED_HOSTS: '["0.0.0.0"]'
        DB_USER: postgres
        DB_PASSWORD: passwd
        DB_HOST: auth-db
        DB_PORT: 5432
        REDIS_HOST: auth-redis
        REDIS_PORT: 6379
      run: docker-compose -f docker-compose.test.yaml up --build --exit-code-from sut
