# name: tests

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   tests:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Unit tests
#       run: docker-compose -f docker-compose.test.yaml up --build --exit-code-from sut

name: tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Unit tests
        run: |
          pip install -r ./requirements/prod.txt -r ./src/tests/functional/requirements.txt
          export PYTHONPATH=./src
          pytest ./src/tests
